name: Execute New SQL Scripts

on:
  push:
    branches:
      - qa

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: List new SQL files
      id: new-sql-files
      run: |
        # Obtener la lista de archivos SQL nuevos desde el último commit en QA
        new_files=$(git diff --name-only origin/qa..HEAD^ -- '*.sql')

        # Si hay archivos nuevos, establecer variable de entorno
        if [ -n "${new_files}" ]; then
          echo "NEW_FILES=${new_files}" >> $GITHUB_ENV
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: Run SQL scripts
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME_QA }}
      run: |
        if [ -n "${{ env.NEW_FILES }}" ]; then
          echo "${{ env.NEW_FILES }}" > new_files.txt
          python execute_sql_scripts.py new_files.txt
        else
          echo "No new SQL files found."
        fi
