name: Execute New SQL Scripts in Prod env

on:
  push:
    branches:
      - main

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: List new SQL files
      id: new-sql-files
      run: |
        # Obtener la lista de archivos SQL nuevos desde el último commit en main
        new_files=$(git diff --name-only origin/main..HEAD^ -- '*.sql')
        echo "NEW_FILES<<EOF" >> $GITHUB_ENV
        echo "${new_files}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: Run SQL scripts
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME_PROD }}
        NEW_FILES: ${{ env.NEW_FILES }}
      run: |
        if [ -n "${NEW_FILES}" ]; then
          echo "${NEW_FILES}" | tr ' ' '\n' > new_files.txt
          python execute_sql_scripts.py new_files.txt
        else
          echo "No new SQL files found."
        fi
