name: Execute New SQL Scripts

on:
  push:
    branches:
      - qa

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get changed SQL files
      id: changed-files
      run: |
        git fetch origin qa
        changed_files=$(git diff --name-only origin/qa HEAD -- '*.sql' || echo '')
        echo "FILES_CHANGED=${changed_files}" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysql-connector-python

    - name: Run SQL scripts
      if: steps.changed-files.outputs.files != ''
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME_QA }}
      run: |
        echo "${{ env.FILES_CHANGED }}" > changed_files.txt
        python execute_sql_scripts.py changed_files.txt
